# Generated by Django 4.2.1 on 2023-05-23 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('Img', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('Img', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('skill', models.CharField(blank=True, max_length=255)),
                ('ficher', models.FileField(blank=True, upload_to='media/')),
                ('Img', models.ImageField(blank=True, upload_to='media/')),
                ('lien_linkedIn', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('acheve', models.BooleanField(default=False)),
                ('rate', models.CharField(choices=[('★☆☆☆☆', '★☆☆☆☆'), ('★★☆☆☆', '★★☆☆☆'), ('★★★☆☆', '★★★☆☆'), ('★★★★☆', '★★★★☆'), ('★★★★★', '★★★★★')], default=1, max_length=50)),
                ('Img', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('clientP', models.ManyToManyField(related_name='projets', to='ArtyProd.client')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ArtyProd.equipe')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Product Design', 'Product Design'), ('UX UI Design', 'UX UI Design'), ('Branding', 'Branding'), ('Digital Strategy', 'Digital Strategy')], max_length=50)),
                ('description', models.TextField()),
                ('Img', models.ImageField(blank=True, null=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_tache', models.CharField(max_length=255)),
                ('fichier', models.FileField(upload_to='media/')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArtyProd.personnel')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='ArtyProd.projet')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArtyProd.service')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('company', models.CharField(max_length=100)),
                ('project_type', models.CharField(max_length=100)),
                ('project_description', models.TextField()),
                ('etat', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], max_length=15)),
                ('file', models.FileField(blank=True, null=True, upload_to='media/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='equipe',
            name='membres',
            field=models.ManyToManyField(to='ArtyProd.personnel'),
        ),
    ]
